### ISSUE TITLE
Extra spaces inside a word with different text formats

### ISSUE THREAD

**Issue by TulioAbreu** [filipedeschamps/parse-google-docs-json#2]
# Version
1.1.1

# System information
Ubuntu 18.04.5 LTS on Windows 11 x86_64
Node v14.17.5

# Issue description

This library will add extra spaces in a word if just part of it has bold/italic/link.

# Steps to reproduce

Given a simple Google Docs example:
![image](https://user-images.githubusercontent.com/33965580/131400188-e4da726a-39e2-4c81-90e3-d11ec833b388.png)

Parsing this snippet, the output will be something like:
```
- Lorem ipsum dolor sit **amet** ;
```
(Extra space between "amet" and ";")

I'm opening this issue to know if this repository is open to contributions and if this is considered a bug or a feature. I found `parse-google-docs-json` snippet inside `gatsby-source-google-docs` handling this test case by matching "before" and "after" token whitespaces and appending those whitespaces on return (https://github.com/cedricdelpoux/gatsby-source-google-docs/blob/master/utils/google-document.js#L51-L62)

**Comment by filipedeschamps** [comment]
Ohhh that's awesome @TulioAbreu sure!! It's definitely a bug 🤝 

If you send a PR we should do a major release, since it can change the outcome considerably 👍

**Comment by TulioAbreu** [comment]
@filipedeschamps 

Fine, I'll submit a pull request 😊

**Comment by filipedeschamps** [comment]
PR merged! You are awesome @TulioAbreu thank you so much! I will release v2 right after 👍
